---
title: 'Assignment #2'
author: "Anna Lizarov"
date: "October 16, 2018"
output: html_document
---

# Part I

```{r}
(D1 <- read.csv("discipline-data.csv", header=TRUE))
```

```{r}
D1$stid <- as.factor(D1$stid)
```

```{r}
library(dplyr)
```
```{r}
D2 <- dplyr::select(D1, tid, stid)
```

```{r}
EDGE <- dplyr::count(D2, tid, stid)

names(EDGE) <- c("from", "to", "count")
EDGE
```

```{r}
#First we will separate the teachers from our original data frame
V.TCH <- dplyr::select(D1, tid, t.gender, t.expertise)
#Remove all the repeats so that we just have a list of each teacher and their characteristics
V.TCH <- unique(V.TCH)
#Add a variable that describes that they are teachers
V.TCH$group <- "teacher"

#Now repeat this process for the students
V.STD <- dplyr::select(D1, stid, s.gender, s.major)
V.STD <- unique(V.STD)
V.STD$group <- "student"

#Make sure that the student and teacher data frames have the same variables names
names(V.TCH) <- c("id", "gender", "topic", "group")
names(V.STD) <- c("id", "gender", "topic", "group")

#Bind the two data frames together (you will get a warning because the teacher data frame has 5 types of id (A,B,C,D,E) and the student has 25 (1-30), this isn't a problem)
VERTEX <- dplyr::bind_rows(V.TCH, V.STD)
```
```{r}
#Load the igraph package

library(igraph)

#First we will make an object that contains the graph information using our two dataframes EDGE and VERTEX. Notice that we have made "directed = TRUE" - our graph is directed since discipline is being given from a teacher to a student.

g <- graph.data.frame(EDGE, directed=TRUE, vertices=VERTEX)

#Now we can plot our graph using the force directed graphing technique - our old friend Fruchertman-Reingold!

plot(g,layout=layout.fruchterman.reingold)

#There are many ways to change the attributes of the graph to represent different characteristics of the newtork. For example, we can color the nodes according to gender.

plot(g,layout=layout.fruchterman.reingold, vertex.color=VERTEX$gender)

#We can change the thickness of the edge according to the number of times a particular teacher has sent a particular student to the principal.

plot(g,layout=layout.fruchterman.reingold, vertex.color=VERTEX$gender, edge.width=EDGE$count)
```
# Part II
```{r}
library(tidyr)
# Disciplinary action count for students
total_st_EDGE <- EDGE %>% group_by(to) %>% summarize(sum(count)) 
names(total_st_EDGE) <- c("id","count")
# Disciplinary action count for teachers
total_t_EDGE <- EDGE %>% group_by(from) %>% summarize(sum(count))
names(total_t_EDGE) <- c("id","count")
total <- bind_rows(total_st_EDGE, total_t_EDGE)
VERTEX <- full_join(VERTEX, total, by="id")
# Graph
gr <- graph.data.frame(EDGE, directed=TRUE, vertices=VERTEX)
plot(gr,layout=layout.fruchterman.reingold, 
     vertex.color=as.factor(VERTEX$gender), 
     edge.arrow.size = 0.5,
     edge.width=EDGE$count,
     vertex.size = VERTEX$count*2)
```

# Part III
```{r}
(cd <- read.csv("HUDK4050-2018-classes.csv", header = TRUE))
```
```{r}
(cd2 <- select(cd, Q8, Q9, Q1, Q3, Q4, Q5, Q6, Q7))
```
```{r}
colnames(cd2) <- as.character(unlist(cd2[1, ]))
cd2 <- cd2[-(1:2), ]
rownames(cd2) <- NULL
cd2
```
```{r}
names(cd2) <- gsub(" ", ".", names(cd2))
cd2
```
```{r}
cd3 <- cd2 %>% unite(First_Last, First.Name, Last.Name, sep="_", remove=TRUE) %>% print
```
```{r}
cd4 <- cd3 %>% gather(Course_Label, Course_Name, Class.1, Class.2, Class.3,Class.4,Class.5, Class.6, na.rm = TRUE, convert = FALSE) %>% print
```
```{r}
(cd4 <- select(cd4, First_Last, Course_Name))
```

```{r}
# Everyone in this dataset is taking HUDK 4050, so I removed it. Otherwise, there is an error message when spreading the dataset.
(cd4 <- filter(cd4, Course_Name>0, Course_Name != "HUDK 4050"))
(cd4 <- filter(cd4, Course_Name != "HUDK4050")) 
```

```{r}
cd4$Count <- 1
```

```{r}
(cd5 <- spread(cd4, Course_Name, Count))
```
```{r}
names(cd5) <- gsub(" ", "", names(cd5))
cd5
```

```{r}
row.names(cd5) <- cd5$First_Last
cd5$First_Last <- NULL
```

```{r}
cd5 <- ifelse(is.na(cd5), 0, 1)
```

```{r}
# Convert from dataframe to matrix
cd6 <- as.matrix(cd5)
```

```{r}
cd7 <- cd6 %*% t(cd6)
diag(cd7) <- NA
```

```{r}
# Graph
sn <- graph.adjacency(cd7, mode= "undirected")
plot(sn, layout=layout.fruchterman.reingold, vertex.size=5 )
```
```{r}
# Centrality
degree(sn)  #degree
```
```{r}
betweenness(sn) #betweenness centrality
```
```{r}
#According to the degree metric, Xixuan Zhao has the greatest number of links to other individuals or nodes in the class network. Likewise, Xixuan Zhao has the greatest betweenness centraility, Thus, Xixuan is the most central person in the network. 
 ```

